version: '3.7'

services:
  docs:
    build:
      context: .
    image: docs
    working_dir: /docs
    container_name: docs
    volumes:
      - ~/dev/docs:/docs
    command: 
      npm install -g docsify-cli@latest
      docsify serve .
    ports:
      - 3000:3000

